### PR TITLE
Restart failing shell components

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Alternative to #84

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Historically, calling `reap()` when handling input was "good enough". But with this enhancement it seems more important to address reaping in a timely manner.

**Comment by mattkae** [comment]
> Historically, calling `reap()` when handling input was "good enough". But with this enhancement it seems more important to address reaping in a timely manner.

Agreed. Is this a limitation of miral code, or can it be done in Miriway?

**Comment by mattkae** [comment]
Ah I see what we're doing. Perhaps we can modify the `ExternalClientLauncher` to optionally notify the caller when a pid dies?

**Comment by AlanGriffiths** [comment]
> Agreed. Is this a limitation of miral code, or can it be done in Miriway?

I'm not sure. Since I adopted the original approach we have added APIs that (for example) allow Frame to use the main loop to poll for filesystem changes. Hopefully, that could help here (but someone needs to find the right APIs to tie it together)

**Comment by AlanGriffiths** [comment]
> someone needs to find the right APIs to tie it together

This looks like a good start:

https://stackoverflow.com/questions/71855507/how-can-i-wait-for-both-a-file-descriptor-and-child-state-change-simultanously

**Review by mattkae — APPROVED** [review]
I am cool with this, knowing that we will have another PR later for the notification on PIDs dying (which I can investigate

**Pull request merged**
